version: '3.8'

services:
  django:
    build:
      context: ./backend/AssistantBackend
    ports:
      - "8000:8000" 
    environment:
      - path_to_env
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  react:
    build:
      context: ./frontend/assistant-frontend
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    environment:
      - path_to_env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # env_file:
    #   - ./.env.dev
    ports:
      - "5432:5432"

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: LOGIN
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
    ports:
      - "5050:80"
    volumes:
    - pgadmin:/var/lib/pgadmin
    depends_on:
    - postgres

volumes:
  postgres_data:
  # pgadmin-d–∞ta:
  pgadmin:
  pgdata:
  static:
  media:
