version: "3.8"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: ./frontend/assistant-frontend/

      dockerfile: Dockerfile
    ports:
      - 80:80

    # environment:
    #   - REACT_APP_URL_BACKEND: http://django:8000

  django:
    build:
      context: ./backend/AssistantBackend
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app/
    command: python manage.py migrate
    ports:
      - 8000:8000

  db:
    restart: always
    image: postgres
    container_name: postgres #you can change this
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin #you can change this
    depends_on:
      - db
    ports:
      - "5050:90"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

volumes:
  postgres_data:
